---

# PLEASE NOTE PRODUCTION READ OF EVENTSTORE IS CURRENTLY WRITING TO TEST BIG QUERY

data_river_eventstore_pagesize: 100

bigquery_project: <bigquery project name>
bigquery_dataset: eventstream
bigquery_auth_project_id: <bigquery project id>
bigquery_auth_client_email: <some name>@<bigquery project name>.iam.gserviceaccount.com
bigquery_auth_client_id: 111
bigquery_auth_uri: https://accounts.google.com/o/oauth2/auth
bigquery_token_uri: https://accounts.google.com/o/oauth2/token
bigquery_auth_provider_x509_cert_url: https://www.googleapis.com/oauth2/v1/certs
bigquery_client_x509_cert_url: <e.g. https://www.googleapis.com/robot/v1/metadata/x509/shinyapps-analytics%40copper-actor-127213.iam.gserviceaccount.com>
bigquery_access_token_path: /secrets/access_token.json
